---

# http://allanmcrae.com/2015/01/replacing-makepkg-asroot/
#
- name: Ensure local AUR directory exits
  become: yes
  file:
    state: directory
    path: '{{ aur_src_dir }}'
    owner: '{{ user_name }}'
    group: 'nobody'
    mode: g+ws
  tags:
    - aur
    - printer:cups:driver:epson:wfc5710dwf

# setfacl -m u::rwx,g::rwx /home/build
# setfacl -d --set u::rwx,g::rwx,o::- /home/build
- name: Ensure correct ACLs on the AUR directory exists (user)
  become: yes
  acl:
    state: present
    path: '{{ aur_src_dir }}'
    entity: '{{ user_name }}'
    etype: user
    permissions: rwx
    default: yes
  tags:
    - aur
    - printer:cups:driver:epson:wfc5710dwf

- name: Ensure correct ACLs on the AUR directory exists (group)
  become: yes
  acl:
    state: present
    path: '{{ aur_src_dir }}'
    entity: nobody
    etype: group
    permissions: rwx
    default: yes
  tags:
    - aur
    - printer:cups:driver:epson:wfc5710dwf

- name: Ensure correct ACLs on the AUR directory exists (others)
  become: yes
  acl:
    state: present
    path: '{{ aur_src_dir }}'
    etype: other
    permissions: '-'
    default: yes
  tags:
    - aur
    - printer:cups:driver:epson:wfc5710dwf


- name: Get printer drivers from the AUR
  become: yes
  become_user: nobody
  git:
    repo: https://aur.archlinux.org/epson-inkjet-printer-escpr2.git
    dest: '{{ aur_src_dir }}/epson-inkjet-printer-escpr2'
  tags:
    - aur
    - printer:cups:driver:epson:wfc5710dwf

- name: Make the printer drivers package
  become: yes
  become_user: nobody
  shell: makepkg --clean --force
  args:
    chdir: '{{ aur_src_dir }}/epson-inkjet-printer-escpr2'
  tags:
    - aur
    - printer:cups:driver:epson:wfc5710dwf

- name: Install the printer drivers package
  become: yes
  shell: pacman --upgrade --noconfirm "$(grep pkgbase .SRCINFO | sed -rn 's/.* = (.*)$/\1/p')-$(grep pkgver .SRCINFO | sed -rn 's/.* = (.*)$/\1/p')-$(grep pkgrel .SRCINFO | sed -rn 's/.* = (.*)$/\1/p')-x86_64.pkg.tar.xz"
  args:
    chdir: '{{ aur_src_dir }}/epson-inkjet-printer-escpr2'
  tags:
    - aur
    - printer:cups:driver:epson:wfc5710dwf

- name: Check if printer already configured
  shell: 2>&1 lpstat -p EPSON_WF-C5710DWF | grep ' EPSON_WF-C5710DWF '
  ignore_errors: yes
  register: lpstat_out
  changed_when: "lpstat_out.rc != 0"
  tags:
    - printer:cups:driver:epson:wfc5710dwf:config

# To find the correct driver and address use lpinfo:
# - Drivers:  lpinfo -m | grep C5710
# - Address:  lpinfo -v
- name: Add Epson WF-C5710 Series printer config
  when: lpstat_out.rc == 1 # The printer was not found
  shell: lpadmin -p EPSON_WF-C5710DWF -E -v lpd://192.168.189.163:515/PASSTHRU -m lsb/usr/epson-inkjet-printer-escpr2/Epson-WF-C5710_Series-epson-escpr2-en.ppd -L "Zuhause im Keller"
  tags:
    - printer:cups:driver:epson:wfc5710dwf:config

- name: Make the Epson WF-C5710 printer the default one
  when: lpstat_out.rc == 1 # The printer was not found
  shell: lpoptions -d EPSON_WF-C5710DWF
  tags:
    - printer:cups:driver:epson:wfc5710dwf:config
